name: MyWeave
favicon: null
layout_spectrum: 0.6047294193413109
typography_spectrum: 0.28782101906836033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4037449765019119
  lightness: 0.37255046027712524
  saturation: 0.0674085607752204
  rhythmicContrast: 0.28972159582190216
purpose: []
