name: MyWeave
favicon: null
layout_spectrum: 0.26541
typography_spectrum: 0.74951
title: 'Wigs and hairpieces for any style or budget!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4275aa'
    - '#013715'
    - '#ffd602'
    - '#e30102'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
