name: MyWeave
favicon: null
layout_spectrum: 0.24751
typography_spectrum: 0.74951
title: 'Wigs and hairpieces for any style or budget!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfdfc'
    - '#e14419'
    - '#641a4f'
    - '#a9ca21'
    - '#000000'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
